### ISSUE TITLE
Seneca comment snippets

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/vscode-seneca-college#5]
From Slack:

> It think one of the things that can be useful is automatic comment header to all of the files that will pre-populate Name, Seneca student Id, course code, etc. Usually, we do it for all programming assignments. This can also have a line about the copyright and code of conduct.

**Comment by catherine-leung** [comment]
This would suggest BB integration.  I think if we are using seneca authentication, getting the email name is possible but I accessing student number I think isn't ... I could be totally wrong about this.  But interesting idea.

**Comment by humphd** [comment]
This could also come from a config file (i.e., the user does setup when installing the extension).

**Comment by Myrfion** [comment]
This sounds like an exciting thing to do, but I am not really familiar with building vs code extensions. I would suppose that as an initial implementation of this feature it can be just made as vs code command that reads some student information from config and puts it on the top of the file, on the top of that it can be attached to some trigger so it is added on the file creation or initial implementation can go without it

**Comment by humphd** [comment]
This could be done similar to the way [Emmet](https://code.visualstudio.com/docs/editor/emmet) works in VSCode for inserting snippets.
